---

- name: disable sudo access of the ubuntu user
  file:
    name: /etc/sudoers.d/90-cloud-init-users
    state: absent
  # Avoid being locked out of the instance before the playbook ends
  when: ansible_user|default("not-ubuntu") != "ubuntu"
