#
# {{ ansible_managed }}
#

global:
  scrape_interval: {{ prometheus_scrape_interval }}
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

rule_files:
  - /etc/prometheus/rules.yml
  - /etc/prometheus/rules.d/*.yml

scrape_configs: {{ prometheus_scrape | to_json }}
