#
# {{ ansible_managed }}
#

apiVersion: 1

deleteDatasources:
  - name: prometheus

datasources:
  # Local prometheus server
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    jsonData:
      timeInterval: {{ prometheus_scrape_interval }}
    editable: false
