on: [push, pull_request]

jobs:
  rust:
    name: Rust projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Rust stable
        run: rustup update stable && rustup default stable

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run the test suite
        run: cargo test --all

      - name: Run clippy
        run: cargo clippy --all -- -Dwarnings

  terraform:
    name: Terraform configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Ensure the terraform files are formatted correctly
        run: terraform fmt -check -diff -recursive

      - name: Validate the terraform directory
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate
